site_name: NEXUS
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      custom_syntax_highlighting: true
  - pymdownx.superfences

nav:
  - Home: index.md
  - Overview & Installation: Overview & Installation.md
  - Basic Syntax: Basic Syntax.md
  - Compound Datatypes: Compound Datatypes.md
  - Conditionals & Loops: Conditionals & Loops.md
  - Functions & Scoping: Functions & Scoping.md
  - Bytecode: Bytecode.md
